CREATE (e1:Event {name: 'GraphConf Wroclaw', date: date('2026-11-12')}),
       (e2:Event {name: 'GraphConf Online', date: date('2026-12-03')}),
       (dm:Topic {name: 'Data modeling'}),
       (rag:Topic {name: 'GraphRAG'}),
       (ops:Topic {name: 'Operations'}),
       (ada:Person {name: 'Ada Nowak', email: 'ada@example.com'}),
       (ben:Person {name: 'Ben Ortiz', email: 'ben@example.com'}),
       (chen:Person {name: 'Chen Li', email: 'chen@example.com'}),
       (dana:Person {name: 'Dana Fischer'}),
       (eli:Person {name: 'Eli Mensah', email: 'eli@example.com'}),
       (t1:Talk {title: 'Graph types in practice'}),
       (t2:Talk {title: 'Reification without regret', level: 'intermediate'}),
       (t3:Talk {title: 'GraphRAG retrievers compared', level: 'advanced'}),
       (t4:Talk {title: 'Running Neo4j migrations in CI', level: 'intermediate'}),
       (t5:Talk {title: 'Ontologies for beginners', level: 'beginner'}),
       (t6:Talk {title: 'Backups you have actually restored', level: 'intermediate'}),
       (ada)-[:PRESENTS]->(t1), (ben)-[:PRESENTS]->(t2), (chen)-[:PRESENTS]->(t3),
       (dana)-[:PRESENTS]->(t4), (eli)-[:PRESENTS]->(t5), (ada)-[:PRESENTS]->(t6),
       (t1)-[:ABOUT]->(dm), (t2)-[:ABOUT]->(dm), (t3)-[:ABOUT]->(rag),
       (t4)-[:ABOUT]->(ops), (t5)-[:ABOUT]->(dm), (t6)-[:ABOUT]->(ops),
       (t1)-[:SCHEDULED_AT {room: 'Hall A', slot: localdatetime('2026-11-12T10:00')}]->(e1),
       (t1)-[:SCHEDULED_AT {room: 'Hall B', slot: localdatetime('2026-11-12T15:00')}]->(e1),
       (t2)-[:SCHEDULED_AT {room: 'Hall A', slot: localdatetime('2026-11-12T11:00')}]->(e1),
       (t3)-[:SCHEDULED_AT {room: 'Hall B', slot: localdatetime('2026-11-12T11:00')}]->(e1),
       (t4)-[:SCHEDULED_AT {room: 'Stream 1', slot: localdatetime('2026-12-03T09:00')}]->(e2),
       (t5)-[:SCHEDULED_AT {room: 'Stream 1', slot: localdatetime('2026-12-03T10:00')}]->(e2),
       (t6)-[:SCHEDULED_AT {room: 'Stream 2', slot: localdatetime('2026-12-03T10:00')}]->(e2);
